blank_issues_enabled: false
contact_links:
  - name: CLI or Core Library Issue
    url: https://github.com/rustledger/rustledger/issues/new/choose
    about: For issues with the rustledger CLI or core library, please use the main repo
  - name: Documentation
    url: https://docs.rs/rustledger-core
    about: View the API documentation
